import {
  AchievementCategory,
  AchievementConditionType,
  AchievementRarity,
  ACHIEVEMENT_RARITY_REWARDS,
} from '@twomc/shared';

export interface SeedAchievement {
  slug: string;
  name: string;
  description: string;
  iconUrl: string;
  category: AchievementCategory;
  rarity: AchievementRarity;
  isSecret?: boolean;
  order: number;
  conditionType: AchievementConditionType;
  conditionValue?: number | null;
  conditionParams?: Record<string, unknown> | null;
  rewardRubies?: number;
  rewardBadgeType?: string | null;
  rewardTitle?: string | null;
  rewardMessage?: string | null;
}

function reward(rarity: AchievementRarity): number {
  return ACHIEVEMENT_RARITY_REWARDS[rarity];
}

export const seedAchievements: SeedAchievement[] = [
  // ─── GAME ───────────────────────────────────────────────
  {
    slug: 'first-login',
    name: 'Первый вход',
    description: 'Войдите на сайт в первый раз',
    iconUrl: '/achievements/first-login.png',
    category: AchievementCategory.GAME,
    rarity: AchievementRarity.COMMON,
    order: 1,
    conditionType: AchievementConditionType.MANUAL,
    conditionValue: 1,
    rewardRubies: reward(AchievementRarity.COMMON),
  },
  {
    slug: 'warmup',
    name: 'Разминка',
    description: 'Проведите 10 минут на сервере',
    iconUrl: '/achievements/warmup.png',
    category: AchievementCategory.GAME,
    rarity: AchievementRarity.COMMON,
    order: 2,
    conditionType: AchievementConditionType.PLAYTIME_MINUTES,
    conditionValue: 10,
    rewardRubies: reward(AchievementRarity.COMMON),
  },
  {
    slug: 'hour-in',
    name: 'Час в игре',
    description: 'Проведите 1 час на сервере',
    iconUrl: '/achievements/hour-in.png',
    category: AchievementCategory.GAME,
    rarity: AchievementRarity.COMMON,
    order: 3,
    conditionType: AchievementConditionType.PLAYTIME_MINUTES,
    conditionValue: 60,
    rewardRubies: reward(AchievementRarity.COMMON),
  },
  {
    slug: 'veteran',
    name: 'Ветеран',
    description: 'Проведите 100 часов на сервере',
    iconUrl: '/achievements/veteran.png',
    category: AchievementCategory.GAME,
    rarity: AchievementRarity.RARE,
    order: 4,
    conditionType: AchievementConditionType.PLAYTIME_MINUTES,
    conditionValue: 6000,
    rewardRubies: reward(AchievementRarity.RARE),
  },
  {
    slug: 'marathon',
    name: 'Марафон',
    description: 'Проведите 500 часов на сервере',
    iconUrl: '/achievements/marathon.png',
    category: AchievementCategory.GAME,
    rarity: AchievementRarity.EPIC,
    order: 5,
    conditionType: AchievementConditionType.PLAYTIME_MINUTES,
    conditionValue: 30000,
    rewardRubies: reward(AchievementRarity.EPIC),
  },
  {
    slug: 'server-legend',
    name: 'Легенда сервера',
    description: 'Проведите 1000 часов на сервере',
    iconUrl: '/achievements/server-legend.png',
    category: AchievementCategory.GAME,
    rarity: AchievementRarity.LEGENDARY,
    order: 6,
    conditionType: AchievementConditionType.PLAYTIME_MINUTES,
    conditionValue: 60000,
    rewardRubies: reward(AchievementRarity.LEGENDARY),
  },
  {
    slug: 'pvp-student',
    name: 'Ученик PvP',
    description: 'Совершите 100 убийств',
    iconUrl: '/achievements/pvp-student.png',
    category: AchievementCategory.GAME,
    rarity: AchievementRarity.COMMON,
    order: 7,
    conditionType: AchievementConditionType.KILLS_COUNT,
    conditionValue: 100,
    rewardRubies: reward(AchievementRarity.COMMON),
  },
  {
    slug: 'pvp-master',
    name: 'Мастер PvP',
    description: 'Совершите 500 убийств',
    iconUrl: '/achievements/pvp-master.png',
    category: AchievementCategory.GAME,
    rarity: AchievementRarity.RARE,
    order: 8,
    conditionType: AchievementConditionType.KILLS_COUNT,
    conditionValue: 500,
    rewardRubies: reward(AchievementRarity.RARE),
  },
  {
    slug: 'pvp-legend',
    name: 'Легенда PvP',
    description: 'Совершите 5000 убийств',
    iconUrl: '/achievements/pvp-legend.png',
    category: AchievementCategory.GAME,
    rarity: AchievementRarity.LEGENDARY,
    order: 9,
    conditionType: AchievementConditionType.KILLS_COUNT,
    conditionValue: 5000,
    rewardRubies: reward(AchievementRarity.LEGENDARY),
  },
  {
    slug: 'first-blood',
    name: 'Первая кровь',
    description: 'Совершите первое убийство',
    iconUrl: '/achievements/first-blood.png',
    category: AchievementCategory.GAME,
    rarity: AchievementRarity.COMMON,
    order: 10,
    conditionType: AchievementConditionType.KILLS_COUNT,
    conditionValue: 1,
    rewardRubies: reward(AchievementRarity.COMMON),
  },
  {
    slug: 'tough-skin',
    name: 'Толстая кожа',
    description: 'Умрите 100 раз',
    iconUrl: '/achievements/tough-skin.png',
    category: AchievementCategory.GAME,
    rarity: AchievementRarity.COMMON,
    order: 11,
    conditionType: AchievementConditionType.DEATHS_COUNT,
    conditionValue: 100,
    rewardRubies: reward(AchievementRarity.COMMON),
  },

  // ─── SOCIAL ─────────────────────────────────────────────
  {
    slug: 'first-friend',
    name: 'Первый друг',
    description: 'Добавьте первого друга',
    iconUrl: '/achievements/first-friend.png',
    category: AchievementCategory.SOCIAL,
    rarity: AchievementRarity.COMMON,
    order: 1,
    conditionType: AchievementConditionType.FRIENDS_COUNT,
    conditionValue: 1,
    rewardRubies: reward(AchievementRarity.COMMON),
  },
  {
    slug: 'popular',
    name: 'Популярный',
    description: 'Наберите 50 друзей',
    iconUrl: '/achievements/popular.png',
    category: AchievementCategory.SOCIAL,
    rarity: AchievementRarity.RARE,
    order: 2,
    conditionType: AchievementConditionType.FRIENDS_COUNT,
    conditionValue: 50,
    rewardRubies: reward(AchievementRarity.RARE),
  },
  {
    slug: 'celebrity',
    name: 'Знаменитость',
    description: 'Наберите 100 друзей',
    iconUrl: '/achievements/celebrity.png',
    category: AchievementCategory.SOCIAL,
    rarity: AchievementRarity.EPIC,
    order: 3,
    conditionType: AchievementConditionType.FRIENDS_COUNT,
    conditionValue: 100,
    rewardRubies: reward(AchievementRarity.EPIC),
  },
  {
    slug: 'talker',
    name: 'Болтун',
    description: 'Оставьте 100 комментариев',
    iconUrl: '/achievements/talker.png',
    category: AchievementCategory.SOCIAL,
    rarity: AchievementRarity.COMMON,
    order: 4,
    conditionType: AchievementConditionType.COMMENTS_COUNT,
    conditionValue: 100,
    rewardRubies: reward(AchievementRarity.COMMON),
  },
  {
    slug: 'chatterbox',
    name: 'Болтушка',
    description: 'Оставьте 1000 комментариев',
    iconUrl: '/achievements/chatterbox.png',
    category: AchievementCategory.SOCIAL,
    rarity: AchievementRarity.RARE,
    order: 5,
    conditionType: AchievementConditionType.COMMENTS_COUNT,
    conditionValue: 1000,
    rewardRubies: reward(AchievementRarity.RARE),
  },
  {
    slug: 'community-voice',
    name: 'Голос сообщества',
    description: 'Оставьте 5000 комментариев',
    iconUrl: '/achievements/community-voice.png',
    category: AchievementCategory.SOCIAL,
    rarity: AchievementRarity.LEGENDARY,
    order: 6,
    conditionType: AchievementConditionType.COMMENTS_COUNT,
    conditionValue: 5000,
    rewardRubies: reward(AchievementRarity.LEGENDARY),
  },
  {
    slug: 'crowd-favorite',
    name: 'Любимец публики',
    description: 'Получите 100 лайков на профиле',
    iconUrl: '/achievements/crowd-favorite.png',
    category: AchievementCategory.SOCIAL,
    rarity: AchievementRarity.RARE,
    order: 7,
    conditionType: AchievementConditionType.LIKES_RECEIVED,
    conditionValue: 100,
    rewardRubies: reward(AchievementRarity.RARE),
  },
  {
    slug: 'well-liked',
    name: 'Нравится всем',
    description: 'Получите 10 лайков на профиле',
    iconUrl: '/achievements/well-liked.png',
    category: AchievementCategory.SOCIAL,
    rarity: AchievementRarity.COMMON,
    order: 8,
    conditionType: AchievementConditionType.LIKES_RECEIVED,
    conditionValue: 10,
    rewardRubies: reward(AchievementRarity.COMMON),
  },
  {
    slug: 'gift-giver',
    name: 'Щедрый',
    description: 'Отправьте 5 подарков',
    iconUrl: '/achievements/gift-giver.png',
    category: AchievementCategory.SOCIAL,
    rarity: AchievementRarity.RARE,
    order: 9,
    conditionType: AchievementConditionType.GIFTS_SENT,
    conditionValue: 5,
    rewardRubies: reward(AchievementRarity.RARE),
  },
  {
    slug: 'gifted',
    name: 'Одарённый',
    description: 'Получите 5 подарков',
    iconUrl: '/achievements/gifted.png',
    category: AchievementCategory.SOCIAL,
    rarity: AchievementRarity.COMMON,
    order: 10,
    conditionType: AchievementConditionType.GIFTS_RECEIVED,
    conditionValue: 5,
    rewardRubies: reward(AchievementRarity.COMMON),
  },

  // ─── DONATION ───────────────────────────────────────────
  {
    slug: 'first-purchase',
    name: 'Первая покупка',
    description: 'Совершите первую покупку в магазине',
    iconUrl: '/achievements/first-purchase.png',
    category: AchievementCategory.DONATION,
    rarity: AchievementRarity.COMMON,
    order: 1,
    conditionType: AchievementConditionType.PURCHASES_COUNT,
    conditionValue: 1,
    rewardRubies: reward(AchievementRarity.COMMON),
  },
  {
    slug: 'regular',
    name: 'Постоянный клиент',
    description: 'Совершите 5 покупок',
    iconUrl: '/achievements/regular.png',
    category: AchievementCategory.DONATION,
    rarity: AchievementRarity.COMMON,
    order: 2,
    conditionType: AchievementConditionType.PURCHASES_COUNT,
    conditionValue: 5,
    rewardRubies: reward(AchievementRarity.COMMON),
  },
  {
    slug: 'true-fan',
    name: 'Настоящий фанат',
    description: 'Совершите 20 покупок',
    iconUrl: '/achievements/true-fan.png',
    category: AchievementCategory.DONATION,
    rarity: AchievementRarity.RARE,
    order: 3,
    conditionType: AchievementConditionType.PURCHASES_COUNT,
    conditionValue: 20,
    rewardRubies: reward(AchievementRarity.RARE),
  },
  {
    slug: 'first-money',
    name: 'Первые деньги',
    description: 'Потратьте 100 ₽ в магазине',
    iconUrl: '/achievements/first-money.png',
    category: AchievementCategory.DONATION,
    rarity: AchievementRarity.COMMON,
    order: 4,
    conditionType: AchievementConditionType.TOTAL_SPENT,
    conditionValue: 100,
    rewardRubies: reward(AchievementRarity.COMMON),
  },
  {
    slug: 'donator',
    name: 'Донатер',
    description: 'Потратьте 1000 ₽ в магазине',
    iconUrl: '/achievements/donator.png',
    category: AchievementCategory.DONATION,
    rarity: AchievementRarity.RARE,
    order: 5,
    conditionType: AchievementConditionType.TOTAL_SPENT,
    conditionValue: 1000,
    rewardRubies: reward(AchievementRarity.RARE),
  },
  {
    slug: 'vip',
    name: 'VIP',
    description: 'Потратьте 10 000 ₽ в магазине',
    iconUrl: '/achievements/vip.png',
    category: AchievementCategory.DONATION,
    rarity: AchievementRarity.EPIC,
    order: 6,
    conditionType: AchievementConditionType.TOTAL_SPENT,
    conditionValue: 10000,
    rewardRubies: reward(AchievementRarity.EPIC),
  },
  {
    slug: 'sponsor',
    name: 'Спонсор',
    description: 'Потратьте 50 000 ₽ в магазине',
    iconUrl: '/achievements/sponsor.png',
    category: AchievementCategory.DONATION,
    rarity: AchievementRarity.LEGENDARY,
    order: 7,
    conditionType: AchievementConditionType.TOTAL_SPENT,
    conditionValue: 50000,
    rewardRubies: reward(AchievementRarity.LEGENDARY),
  },
  {
    slug: 'patron',
    name: 'Меценат',
    description: 'Потратьте 100 000 ₽ в магазине',
    iconUrl: '/achievements/patron.png',
    category: AchievementCategory.DONATION,
    rarity: AchievementRarity.MYTHIC,
    order: 8,
    conditionType: AchievementConditionType.TOTAL_SPENT,
    conditionValue: 100000,
    rewardRubies: reward(AchievementRarity.MYTHIC),
  },

  // ─── SPECIAL ────────────────────────────────────────────
  {
    slug: 'anniversary',
    name: 'Годовщина',
    description: 'Аккаунту исполнился 1 год',
    iconUrl: '/achievements/anniversary.png',
    category: AchievementCategory.SPECIAL,
    rarity: AchievementRarity.EPIC,
    order: 1,
    conditionType: AchievementConditionType.ACCOUNT_AGE_DAYS,
    conditionValue: 365,
    rewardRubies: reward(AchievementRarity.EPIC),
  },
  {
    slug: 'pioneer',
    name: 'Пионер',
    description: 'Войдите в первую сотню зарегистрированных игроков',
    iconUrl: '/achievements/pioneer.png',
    category: AchievementCategory.SPECIAL,
    rarity: AchievementRarity.LEGENDARY,
    order: 2,
    conditionType: AchievementConditionType.REGISTRATION_ORDER,
    conditionValue: 100,
    rewardRubies: reward(AchievementRarity.LEGENDARY),
  },
  {
    slug: 'first-registrar',
    name: 'Первопроходец',
    description: 'Зарегистрируйтесь в первый месяц работы сайта',
    iconUrl: '/achievements/first-registrar.png',
    category: AchievementCategory.SPECIAL,
    rarity: AchievementRarity.EPIC,
    order: 3,
    conditionType: AchievementConditionType.CUSTOM,
    conditionValue: 1,
    conditionParams: { type: 'first_month' },
    rewardRubies: reward(AchievementRarity.EPIC),
  },
  {
    slug: 'collector',
    name: 'Коллекционер',
    description: 'Соберите 3 бейджа',
    iconUrl: '/achievements/collector.png',
    category: AchievementCategory.SPECIAL,
    rarity: AchievementRarity.RARE,
    order: 4,
    conditionType: AchievementConditionType.BADGES_COUNT,
    conditionValue: 3,
    rewardRubies: reward(AchievementRarity.RARE),
  },

  // ─── DAILY ──────────────────────────────────────────────
  {
    slug: 'comeback',
    name: 'Возвращение',
    description: 'Заходите на сайт 3 дня подряд',
    iconUrl: '/achievements/comeback.png',
    category: AchievementCategory.DAILY,
    rarity: AchievementRarity.COMMON,
    order: 1,
    conditionType: AchievementConditionType.DAYS_STREAK,
    conditionValue: 3,
    rewardRubies: reward(AchievementRarity.COMMON),
  },
  {
    slug: 'consistent',
    name: 'Постоянство',
    description: 'Заходите на сайт 7 дней подряд',
    iconUrl: '/achievements/consistent.png',
    category: AchievementCategory.DAILY,
    rarity: AchievementRarity.COMMON,
    order: 2,
    conditionType: AchievementConditionType.DAYS_STREAK,
    conditionValue: 7,
    rewardRubies: reward(AchievementRarity.COMMON),
  },
  {
    slug: 'adherent',
    name: 'Приверженец',
    description: 'Заходите на сайт 14 дней подряд',
    iconUrl: '/achievements/adherent.png',
    category: AchievementCategory.DAILY,
    rarity: AchievementRarity.RARE,
    order: 3,
    conditionType: AchievementConditionType.DAYS_STREAK,
    conditionValue: 14,
    rewardRubies: reward(AchievementRarity.RARE),
  },
  {
    slug: 'loyal',
    name: 'Лояльный',
    description: 'Заходите на сайт 30 дней подряд',
    iconUrl: '/achievements/loyal.png',
    category: AchievementCategory.DAILY,
    rarity: AchievementRarity.EPIC,
    order: 4,
    conditionType: AchievementConditionType.DAYS_STREAK,
    conditionValue: 30,
    rewardRubies: reward(AchievementRarity.EPIC),
  },
  {
    slug: 'steadfast',
    name: 'Стойкий',
    description: 'Заходите на сайт 60 дней подряд',
    iconUrl: '/achievements/steadfast.png',
    category: AchievementCategory.DAILY,
    rarity: AchievementRarity.LEGENDARY,
    order: 5,
    conditionType: AchievementConditionType.DAYS_STREAK,
    conditionValue: 60,
    rewardRubies: reward(AchievementRarity.LEGENDARY),
  },
  {
    slug: 'site-veteran',
    name: 'Ветеран сайта',
    description: 'Заходите на сайт 100 дней подряд',
    iconUrl: '/achievements/site-veteran.png',
    category: AchievementCategory.DAILY,
    rarity: AchievementRarity.MYTHIC,
    order: 6,
    conditionType: AchievementConditionType.DAYS_STREAK,
    conditionValue: 100,
    rewardRubies: reward(AchievementRarity.MYTHIC),
  },

  // ─── SECRET ─────────────────────────────────────────────
  {
    slug: 'tracker',
    name: 'Следопыт',
    description: 'Просмотрите 100 профилей',
    iconUrl: '/achievements/tracker.png',
    category: AchievementCategory.SECRET,
    rarity: AchievementRarity.RARE,
    isSecret: true,
    order: 1,
    conditionType: AchievementConditionType.PROFILE_VIEWS,
    conditionValue: 100,
    rewardRubies: reward(AchievementRarity.RARE),
  },
  {
    slug: 'ninja',
    name: 'Ниндзя',
    description: 'Будьте активны на сайте между 2:00 и 4:00',
    iconUrl: '/achievements/ninja.png',
    category: AchievementCategory.SECRET,
    rarity: AchievementRarity.EPIC,
    isSecret: true,
    order: 2,
    conditionType: AchievementConditionType.CUSTOM,
    conditionValue: 1,
    conditionParams: { type: 'night_owl', fromHour: 2, toHour: 4 },
    rewardRubies: reward(AchievementRarity.EPIC),
  },
  {
    slug: 'bug-hunter',
    name: 'Охотник за багами',
    description: 'Сообщите о технической проблеме, которая была решена',
    iconUrl: '/achievements/bug-hunter.png',
    category: AchievementCategory.SECRET,
    rarity: AchievementRarity.EPIC,
    isSecret: true,
    order: 3,
    conditionType: AchievementConditionType.BUG_REPORTED,
    conditionValue: 1,
    rewardRubies: reward(AchievementRarity.EPIC),
  },
  {
    slug: 'easter-egg',
    name: 'Пасхалка',
    description: 'Найдите секретную страницу',
    iconUrl: '/achievements/easter-egg.png',
    category: AchievementCategory.SECRET,
    rarity: AchievementRarity.LEGENDARY,
    isSecret: true,
    order: 4,
    conditionType: AchievementConditionType.MANUAL,
    conditionValue: 1,
    rewardRubies: reward(AchievementRarity.LEGENDARY),
    rewardMessage: 'Вы нашли то, что искали…',
  },
];
