export const queryKeys = {
  me: ['auth', 'me'] as const,
  profile: (username: string) => ['profile', username] as const,
  myProfile: ['profile', 'me'] as const,
  friends: (page?: number, search?: string) => ['friends', 'list', page ?? 1, search ?? ''] as const,
  incomingRequests: (page?: number) => ['friends', 'incoming', page ?? 1] as const,
  outgoingRequests: (page?: number) => ['friends', 'outgoing', page ?? 1] as const,
  blockedUsers: (page?: number) => ['friends', 'blocked', page ?? 1] as const,
  friendStatus: (username: string) => ['friends', 'status', username] as const,
  friendsCount: (username?: string) =>
    username ? (['friends', 'count', username] as const) : (['friends', 'count', 'me'] as const),
  incomingCount: ['friends', 'incoming-count'] as const,
  positions: (group?: string) => ['positions', group ?? 'all'] as const,
  position: (slug: string) => ['positions', 'slug', slug] as const,
  comments: (username: string, page?: number, sort?: string) =>
    ['comments', username, page ?? 1, sort ?? 'newest'] as const,
  awards: ['awards'] as const,
  notifications: (filters: Record<string, unknown>) =>
    ['notifications', 'list', filters] as const,
  notificationsUnreadCount: ['notifications', 'unread-count'] as const,
  storeCategories: ['store', 'categories'] as const,
  storeProducts: (filters: Record<string, unknown>) =>
    ['store', 'products', filters] as const,
  storeProduct: (slug: string) => ['store', 'product', slug] as const,
  storeBundles: ['store', 'bundles'] as const,
  storeBundle: (slug: string) => ['store', 'bundle', slug] as const,
  storeCart: ['store', 'cart'] as const,
  storeWishlist: ['store', 'wishlist'] as const,
  storeUserWishlist: (username: string) =>
    ['store', 'wishlist', 'user', username] as const,
  storeOrders: (page?: number) => ['store', 'orders', page ?? 1] as const,
  storeOrder: (orderNumber: string) => ['store', 'order', orderNumber] as const,
  storeBulkDiscounts: ['store', 'bulk-discounts'] as const,
  storeCurrencies: ['store', 'currencies'] as const,
  storeCurrencyRates: ['store', 'currency-rates'] as const,
  storeRecentPurchases: (limit?: number) =>
    ['store', 'recent-purchases', limit ?? 12] as const,
  storeBoughtTogether: (productId: string) =>
    ['store', 'bought-together', productId] as const,
  adminStoreCategories: ['admin', 'store', 'categories'] as const,
  adminStoreProducts: ['admin', 'store', 'products'] as const,
  adminStoreBundles: ['admin', 'store', 'bundles'] as const,
  adminBulkDiscounts: ['admin', 'store', 'bulk-discounts'] as const,
  adminLoyalty: ['admin', 'store', 'loyalty'] as const,
  adminPromocodes: ['admin', 'promocodes'] as const,
  adminOrders: (filters?: Record<string, unknown>) =>
    ['admin', 'orders', filters ?? {}] as const,
  adminOrderStats: ['admin', 'orders', 'stats'] as const,
  adminStoreStats: ['admin', 'store', 'stats'] as const,
  chatChannels: ['chat', 'channels'] as const,
  chatChannel: (slug: string) => ['chat', 'channel', slug] as const,
  chatMessages: (slug: string) => ['chat', 'messages', slug] as const,
  chatOnline: (slug: string) => ['chat', 'online', slug] as const,
  chatPinned: (slug: string) => ['chat', 'pinned', slug] as const,
  servers: ['servers', 'list'] as const,
  serverCategories: ['servers', 'categories'] as const,
  serversOverview: ['servers', 'overview'] as const,
  server: (slug: string) => ['servers', 'detail', slug] as const,
  serverStatus: (slug: string) => ['servers', 'status', slug] as const,
  serverHistory: (slug: string, days: number) =>
    ['servers', 'history', slug, days] as const,
  serverPlayers: (slug: string) => ['servers', 'players', slug] as const,
  adminServers: ['admin', 'servers'] as const,
  adminServerLogs: (id: string, filters?: Record<string, unknown>) =>
    ['admin', 'servers', 'logs', id, filters ?? {}] as const,
  topics: (filters: Record<string, unknown>) => ['topics', filters] as const,
  topic: (slug: string) => ['topics', 'detail', slug] as const,
  adminTopics: ['admin', 'topics'] as const,
  adminTopic: (id: string) => ['admin', 'topics', id] as const,
  reports: (filters: Record<string, unknown>) => ['reports', 'list', filters] as const,
  report: (reportNumber: string) => ['reports', 'detail', reportNumber] as const,
  reportRules: (type: string) => ['reports', 'rules', type] as const,
  moderationReports: (filters: Record<string, unknown>) =>
    ['moderation', 'reports', filters] as const,
  donationReports: (filters: Record<string, unknown>) =>
    ['admin', 'support', 'donations', filters] as const,
  reportStats: ['admin', 'reports', 'stats'] as const,
  myPunishments: (onlyAppealable?: boolean) =>
    ['users', 'me', 'punishments', onlyAppealable ?? false] as const,
  userSearchHint: (username: string) => ['users', 'search-hint', username] as const,
  myReportStats: ['reports', 'my-stats'] as const,
  news: (filters: Record<string, unknown>) => ['news', 'list', filters] as const,
  newsFeatured: ['news', 'featured'] as const,
  newsLatest: (limit: number) => ['news', 'latest', limit] as const,
  newsPopular: ['news', 'popular'] as const,
  newsBySlug: (slug: string) => ['news', 'detail', slug] as const,
  newsCategories: ['news', 'categories'] as const,
  newsTags: (limit: number) => ['news', 'tags', limit] as const,
  newsComments: (slug: string, filters?: Record<string, unknown>) =>
    ['news', 'comments', slug, filters ?? {}] as const,
  adminNews: (filters: Record<string, unknown>) => ['admin', 'news', filters] as const,
  adminNewsItem: (id: string) => ['admin', 'news', id] as const,
  adminNewsStats: ['admin', 'news', 'stats'] as const,
  activityFeed: (filters: Record<string, unknown>) =>
    ['activity', 'feed', filters] as const,
  activityHighlights: (period: string) => ['activity', 'highlights', period] as const,
  activityById: (id: string) => ['activity', 'detail', id] as const,
  userActivity: (username: string, filters?: Record<string, unknown>) =>
    ['activity', 'user', username, filters ?? {}] as const,
  activitySettings: ['activity', 'settings'] as const,
  adminActivity: (filters: Record<string, unknown>) =>
    ['admin', 'activity', filters] as const,
  adminActivityStats: ['admin', 'activity', 'stats'] as const,
};
